### ISSUE TITLE
Error in Object.convertBoard

### ISSUE THREAD

**Issue by holmesrichards** [wokwi/easyeda2kicad#19]
I get an error trying to convert:

```
$ easyeda2kicad ~/123ADC.json ~/123ADC.kicad_pcb
/usr/local/lib/nodejs/node-v12.14.1-linux-x64/lib/node_modules/easyeda2kicad/dist/board.js:379
    var outputObjs = __spreadArrays(nets.map(function (net, idx) { return ['net', idx, net]; }), flatten(input.shape.map(function (shape) { return convertShape(shape, nets); }))).filter(function (obj) { return obj != null; });
                                                                                                                     ^

TypeError: Cannot read property 'map' of undefined
    at Object.convertBoard (/usr/local/lib/nodejs/node-v12.14.1-linux-x64/lib/node_modules/easyeda2kicad/dist/board.js:379:118)
    at Object.<anonymous> (/usr/local/lib/nodejs/node-v12.14.1-linux-x64/lib/node_modules/easyeda2kicad/dist/main.js:18:42)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11

$ easyeda2kicad -v
Version 1.3.4
$ node -v
v12.14.1
```

OS is Linux Mint 19.2. KiCad version `5.1.5-52549c5~84~ubuntu18.04.1
`
Attached file is what I attempted to import.

[123ADC.json.zip](https://github.com/wokwi/easyeda2kicad/files/4146214/123ADC.json.zip)

**Comment by urish** [comment]
Hi @holmesrichards , I looked into this file and this seems to be a schematics file (and not PCB layout). Schematic files are not currently supported (see #2), but as @karinchechik has started working on this, it will probably be possible in a few weeks from now.
