### ISSUE TITLE
can't run easyeda2kicad

### ISSUE THREAD

**Issue by jcabdi** [wokwi/easyeda2kicad#91]
I'm in Ubuntu 20.04

jcabdi@jc-dell:~/Downloads/easyeda2kicad-0.6.3/easyeda2kicad$ easyeda2kicad
Traceback (most recent call last):
  File "/home/jcabdi/.local/bin/easyeda2kicad", line 5, in <module>
    from easyeda2kicad.__main__ import main
  File "/home/jcabdi/.local/lib/python3.8/site-packages/easyeda2kicad/__main__.py", line 12, in <module>
    from easyeda2kicad.easyeda.easyeda_importer import (
  File "/home/jcabdi/.local/lib/python3.8/site-packages/easyeda2kicad/easyeda/easyeda_importer.py", line 6, in <module>
    from easyeda2kicad.easyeda.parameters_easyeda import *
  File "/home/jcabdi/.local/lib/python3.8/site-packages/easyeda2kicad/easyeda/parameters_easyeda.py", line 26, in <module>
    class EeSymbolPinSettings(BaseModel):
  File "/home/jcabdi/.local/lib/python3.8/site-packages/pydantic/_internal/_model_construction.py", line 130, in __new__
    cls.__pydantic_decorators__ = DecoratorInfos.build(cls)
  File "/home/jcabdi/.local/lib/python3.8/site-packages/pydantic/_internal/_decorators.py", line 441, in build
    res.validators[var_name] = Decorator.build(
  File "/home/jcabdi/.local/lib/python3.8/site-packages/pydantic/_internal/_decorators.py", line 249, in build
    func = shim(func)
  File "/home/jcabdi/.local/lib/python3.8/site-packages/pydantic/_internal/_decorators_v1.py", line 77, in make_generic_v1_field_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: The `field` and `config` parameters are not available in Pydantic V2, please use the `info` parameter instead.

For further information visit https://errors.pydantic.dev/2.2/u/validator-field-config-info

**Comment by JulioCalandrin** [comment]
Had the exact same error on Windows 11.
Edit: After uninstalling Pydantic V2 and Pydantic_core V2 I reinstalled the V1 via "pip install Pydantic==1.5". It worked after this.

**Comment by stellarpower** [comment]
FYI, you are looking at this project: https://github.com/uPesy/easyeda2kicad.py
This one is written in TypeScript, not python.
